### ISSUE TITLE
Cluster Split fail and raise Exception!

### ISSUE THREAD

**Issue by yingyi-ma** [OpenDroneMap/ClusterODM#30]
700 photos to split

CMD:
`docker run -ti -v "/ftpfile/1400/1400:/code/images" opendronemap/odm --split 400 --split-overlap 100 --sm-cluster http://192.168.3.86:3100`

cluster: http://192.168.3.86:3100 
config :
```
#> node list
1) 192.168.3.86:3001 [online] [0/2] <version 1.5.3>
2) 192.168.3.86:3002 [online] [0/2] <version 1.5.3>
3) 192.168.3.86:3003 [online] [0/2] <version 1.5.3>
4) 192.168.3.86:3005 [online] [0/2] <version 1.5.3>
5) 192.168.3.86:3006 [online] [0/2] <version 1.5.3>
6) 192.168.3.86:3009 [online] [0/2] <version 1.5.3>

```

EXCEPTION:
```
OpenCV Error: Assertion failed (data0.dims <= 2 && type == CV_32F && K > 0) in kmeans, file /code/SuperBuild/src/opencv/modules/core/src/matrix.cpp, line 2701
Traceback (most recent call last):
  File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/create_submodels.py", line 30, in run
    self._cluster_images(meta_data, data.config['submodel_size'])
  File "/code/SuperBuild/src/opensfm/opensfm/commands/create_submodels.py", line 100, in _cluster_images
    labels, centers = tools.kmeans(positions, K)[1:]
  File "/code/SuperBuild/src/opensfm/opensfm/large/tools.py", line 34, in kmeans
    return cv2.kmeans(samples, nclusters, criteria, attempts, flags)
cv2.error: /code/SuperBuild/src/opencv/modules/core/src/matrix.cpp:2701: error: (-215) data0.dims <= 2 && type == CV_32F && K > 0 in function kmeans

Traceback (most recent call last):
  File "/code/run.py", line 56, in <module>
    app.execute()
  File "/code/stages/odm_app.py", line 93, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 376, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 357, in run
    self.process(self.args, outputs)
  File "/code/stages/splitmerge.py", line 65, in process
    octx.run("create_submodels")
  File "/code/opendm/osfm.py", line 21, in run
    (context.opensfm_path, command, self.opensfm_project_path))
  File "/code/opendm/system.py", line 76, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

**Comment by yingyi-ma** [comment]
Help !  and Why?

**Comment by pierotofy** [comment]
Hey @yingyi-ma :hand: do your images have EXIF GPS information embedded in them?

**Comment by yingyi-ma** [comment]
> Hey @yingyi-ma ✋ do your images have EXIF GPS information embedded in them?

Thank you so much ! 
It's really because there is no GPS information in the picture.😄😄😄

**Comment by pierotofy** [comment]
Yeah, if you don't have GPS you'll have to create an `image_groups.txt` file as explained in https://docs.opendronemap.org/large.html#local-split-merge. I've opened https://github.com/OpenDroneMap/ODM/issues/1012 to improve the error message in the future.
